name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    uses: Taure/erlang-ci/.github/workflows/ci.yml@v2.0.9
    with:
      version-file: '.tool-versions'
      enable-eunit: false
      enable-ex-doc: false
      enable-audit: false
      enable-sbom: true
      enable-sbom-scan: true
      enable-dependency-submission: true
      enable-summary: true
      enable-elp-lint: true
      enable-elp-eqwalize: true
